### ISSUE TITLE
Developer-Zone Wiki link to a ‘Sandbox’ Connector API

### ISSUE THREAD

**Issue by B-Whitt** [IBM/IFT-Developer-Zone#2]
Should the IFT-Developer-Zone Wiki (https://github.com/IBM/IFT-Developer-Zone/wiki) link to a ‘Sandbox’ environment Connector API? Is the Sandbox environment still supported?

![image](https://user-images.githubusercontent.com/34513926/47381725-b0a4d680-d6ce-11e8-8842-4aac125d15c0.png)

**Comment by joshhus** [comment]
Page has since been updated.
