### ISSUE TITLE
Custom fields in EPCIS messages

### ISSUE THREAD

**Issue by keyanmk2** [IBM/IFT-Developer-Zone#6]
Hello, we have use cases where we wish to transmit custom fields along with its value as part of EPCIS messages. We know GS1 EPCIS has provisions for the same, but the question is, how does IBM Food Trust platform handle those values? Does it appear as part of the UI when the user consumes these events? Thank you.

**Comment by keyanmk2** [comment]
Guys, your response would be much appreciated. Thank you

**Comment by joshhus** [comment]
@keyanmk2 Apologies, this repo was not being monitored for support questions at the time. Is this still a question for you?

**Comment by joshhus** [comment]
No response from originator, closing.
