### ISSUE TITLE
Label missing in documentation page

### ISSUE THREAD

**Issue by ghost** [IBM/IFT-Developer-Zone#7]
The onboarding spreadsheet in row 23 points to https://github.com/IBM/IFT-Developer-Zone/wiki/how-to-upload-data-to-IFT#manual-submission but the label "manual-submission is not available in the page.
Regards.

**Comment by joshhus** [comment]
https://github.ibm.com/FoodSafety/documentation/issues/278

**Comment by joshhus** [comment]
had been tracked in documentation repo closing.
